CREATE DATABASE IF NOT EXISTS linsta;

USE linsta;

CREATE TABLE IF NOT EXISTS Users (
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    ID INT AUTO_INCREMENT UNIQUE,
    AGE INT NOT NULL,
    EMAIL VARCHAR(256) UNIQUE NOT NULL,
    PHONE VARCHAR(16) UNIQUE NOT NULL,
    USERNAME varchar(64) UNIQUE NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    JOIN_DATE DATETIME NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ConfirmCodes (
    CODE varchar(6) NOT NULL,
    USER_DATA VARCHAR(256) NOT NULL UNIQUE,
    SENT_TIME DATETIME not null
)

CREATE TABLE IF NOT EXISTS ForgotToken (
    TOKEN VARCHAR(256) NOT NULL UNIQUE,
    USER_ID INT NOT NULL UNIQUE,
    
    CONSTRAINT FK_USER_ID_FORGOT FOREIGN KEY (USER_ID) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Follows (
	ID INT auto_increment,
	USER_ID INT NOT NULL,
    FOLLOWS_USER_ID INT NOT NULL,
    
    CONSTRAINT FK_USER_ID1 FOREIGN KEY (USER_ID) REFERENCES Users(ID),
    CONSTRAINT FK_FOLLOWS_ID FOREIGN KEY (FOLLOWS_USER_ID) REFERENCES Users(ID),
    
    PRIMARY KEY(id), 
    UNIQUE KEY(USER_ID, FOLLOWS_USER_ID) 
);