CREATE DATABASE IF NOT EXISTS linsta;

USE linsta;

CREATE TABLE IF NOT EXISTS Users (
    FIRST_NAME VARCHAR(128) NOT NULL,
    LAST_NAME VARCHAR(128) NOT NULL,
    ID INT AUTO_INCREMENT UNIQUE,
    AGE INT NOT NULL,
    EMAIL VARCHAR(256) /*UNIQUE*/ NOT NULL,
    PHONE VARCHAR(16) NOT NULL,
    USERNAME varchar(64) UNIQUE NOT NULL,
    BITHDATE DATE NOT NULL,
    JOIN_DATE DATETIME NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Profiles (
    ID INT AUTO_INCREMENT,
    PRONOUNS VARCHAR(16),
    PROFILE_TEXT VARCHAR(1024),
    PROFILE_IMAGE_URL VARCHAR(4096),
    USER_ID INT NOT NULL UNIQUE,

    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES Users(ID),

    PRIMARY KEY (ID);     
);