pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                sh "docker-compose build"
                sh "docker-compose up -d"
                sleep(45)
            }
        }

    }
    post {
        always {
            sh "docker-compose down || true"
        }
    }
}