pipeline {
    agent any
    stages {
        stage("Build") {
            steps {
                sh "docker-compose build"
                sh "docker-compose up -d"
                waitUntilServicesReady
            }
        }
        stage("Run Tests") {
            steps {

            }
        }
    }
    post {
        always {
            sh "docker-compose down || true"
        }
    }
}