{
 "title": "Back-End",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Comments",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "target": "stats.comments.*.invoked" }
   ]
  },
  {
   "title": "Profiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "target": "stats.profiles.*.invoked" }
   ]
  },
  {
   "title": "Accounts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "target": "stats.accounts.*" }
   ]
  },
  {
   "title": "Posts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "target": "stats.posts.*.invoked" }
   ]
  },
  {
   "title": "Search",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    { "target": "stats.search.*.invoked" }
   ]
  },
  {
   "title": "Locations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "target": "stats.location.getlocation.invoked"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "target": "stats.gauges.redis.usedMemory" },
    {
     "target": "stats.gauges.redis.usedMemoryPeak"
    }
   ]
  },
  {
   "title": "Key Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    { "target": "stats.gauges.redis.keyCount" }
   ]
  },
  {
   "title": "Mem Fragmentation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "target": "stats.gauges.redis.memFragmentationRatio"
    }
   ]
  },
  {
   "title": "Connected Clients",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.redis.connectedClients"
    }
   ]
  },
  { "title": "ElasticSearch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Doc Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "target": "stats.gauges.es.total_docs_count"
    }
   ]
  },
  {
   "title": "Cluster Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.es.cluster_status" }
   ]
  },
  {
   "title": "Num Nodes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 43 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.es.number_of_nodes"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "target": "stats.gauges.es.active_shards" }
   ]
  },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.es.active_primary_shards"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.es.unassigned_shards"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.es.number_of_pending_tasks"
    }
   ]
  }
 ]
}